version: '3'
services:
  homeassistant:
    container_name: homeassistant
    image: homeassistant/home-assistant:stable
    privileged: true
    restart: always
    volumes:
      - ./homeassistant:/config
    environment:
      - TZ=Europe/Paris
    # network_mode: host
    ports:
      - 8123:8123

  mqtt:
    container_name: mqtt
    image: eclipse-mosquitto
    restart: always
    ports:
      - 1883:1883
  
  ipx:
    container_name: ipx
    image: leclubber/ipx2mqtt
    privileged: true
    restart: always
    # build: ./ipx
    ports:
      - 8080:8080
    environment:
      - HTTP_PORT=8080
      - MQTT_PORT=1883
      - MQTT_HOST=mqtt
      - MQTT_TOPIC=ipx
      - IPX_HOST=192.168.1.1
      - IPX_API_KEY=apikey
      - IPX_LOGIN=admin
      - IPX_PASSWORD=password
      - IPX_PULL_STATUS=3
      - IPX_RELAY_LIGHT=17-19,25
      - IPX_RELAY_SWITCH=50-53
      - IPX_DIMMER=d1c1,d1c2

